### PR TITLE
Shortcut creation: use fallback miniature/icon if miniature/icon cannot be accessed

### LINKED ISSUE #1534: Exception when trying to edit a shortcut
It fails in `ShortcutManager` for `shortcutDTO.getIcon()` because the default (`phoenicis.png` inside the jar) cannot be used as a file.

### PR DESCRIPTION
**Pull request by plata**
Fixes #1534

### CODE REVIEW

File: phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java [hunk 1]
```diff
@@ -79,7 +79,13 @@ public void createShortcut(ShortcutDTO shortcutDTO) {
 
             try {
                 if (shortcutDTO.getIcon() != null) {
-                    File file = new File(shortcutDTO.getIcon());
+                    File file;
```
Comment (madoar) [inline phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java]: Can we maybe move the `File` creation to a new method?
I mean both changes look equal to me with the difference of two parts, which could be specified using two input parameters.

Comment (plata) [reply phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java]: Technically that's of course possible but honestly it doesn't make much sense for me. If you really want it, I can do it.

Comment (madoar) [reply phoenicis-library/src/main/java/org/phoenicis/library/ShortcutManager.java]: I don't really like this kind of object creation where we begin with `File file;`.
Therefore I think a function would be a more clean solution for this.
