### PR TITLE
Fix the engines filter

### LINKED ISSUE #1562: Missing Wine engine after searching for an engine
### Expected behavior
grafik

### Actual behavior
grafik

### Steps to reproduce
Open engines tab and enter "League" in the search field

### PR DESCRIPTION
**Pull request by madoar**
Fixes #1562.

This PR is part of #1536

### CODE REVIEW

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java [hunk 1]
```diff
@@ -161,9 +161,11 @@ private boolean isInstalled(EngineCategoryDTO engineCategory, EngineSubCategoryD
...
      */
     public boolean filter(EngineCategoryDTO engineCategory) {
-        return searchTerm.map(
-                searchTerm -> engineCategory.getSubCategories().stream().anyMatch(engineSubCategory -> engineSubCategory
-                        .getPackages().stream().anyMatch(version -> version.getVersion().contains(searchTerm))))
+        return searchTerm
+                .map(searchTerm -> engineCategory.getSubCategories().stream()
+                        .anyMatch(engineSubCategory -> engineSubCategory.getPackages().stream()
+                                .anyMatch(version -> version.getVersion().toLowerCase()
+                                        .contains(searchTerm.toLowerCase()))))
```
Comment (plata) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java]: Not really related to this issue but should we use fuzzy search here as well (like for apps)?

Comment (madoar) [reply phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/engines/EnginesFilter.java]: True
