### PR TITLE
Run AppConfigurationInitialisationTest in a temporary application.user.root

### LINKED ISSUE #1402: Folder '...' is no git-repository
### Expected behavior
Phoenicis starts correctly

### Actual behavior
Phoenicis doesn't start correctly with an error message containing: `Folder '...' is no git-repository`. (see also #1401)

### Steps to reproduce
This issue occurs sometimes. I'm not really sure what the reason for the bug is, but in all cases I know of, a manual deletion of the folder and a restart of Phoenicis has solved the issue.

### PR DESCRIPTION
**Pull request by plata**
fixes #1402 (test creates an empty git folder)

### CODE REVIEW

File: phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java [hunk 1]
```diff
@@ -1,26 +1,37 @@
...
  */
 public class AppConfigurationInitialisationTest {
 
+    /**
+     * run the test in a temporary application root environment
+     */
+    private static void setupApplicationRoot() throws IOException {
+        Path tempDir = Files.createTempDirectory(AppConfigurationInitialisationTest.class.getName());
+        tempDir.toFile().deleteOnExit();
+        System.setProperty("application.user.root", tempDir.toString());
```
Comment (madoar) [inline phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java]: This sounds like something we want to do in a `@BeforeClass` annotated method.

File: phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java [hunk 2]
```diff
@@ -29,10 +40,17 @@ public static void setupHeadless() {
...
-        setupHeadless();
-        FxToolkit.registerPrimaryStage();
-        FxToolkit.setupFixture(() -> new AnnotationConfigApplicationContext(AppConfiguration.class));
+    public void testAppConfigurationInitialisation() {
+        try {
+            setupApplicationRoot();
+            setupHeadless();
+            FxToolkit.registerPrimaryStage();
+            FxToolkit.setupFixture(() -> new AnnotationConfigApplicationContext(AppConfiguration.class));
+        } catch (TimeoutException | IOException e) {
```
Comment (madoar) [inline phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java]: Why don't we continue to forward the exceptions to junit?

Comment (plata) [reply phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java]: Codacy was complaining that the test didn't contain `fail` or `assert`.

File: phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java (hunk 1 above)
Comment (plata) [reply phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java]: Why should it be different than the setup for headless?

Comment (madoar) [reply phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java]: It shouldn't.
I think we should move the headless initialization to a method annotated with `@BeforeClass` too.
I don't know why I didn't do that initially...

Comment (plata) [reply phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java]: Maybe because I wrote that method ;) (you had it in maven).
